apiVersion: v1
kind: Service
metadata:
    name: "datapower"
spec:
    selector:
        app: "datapower"
    type: NodePort
    ports:
        - port: 9090
          name: mpgw
          protocol: TCP
          targetPort: 9090
